name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            set -e

            echo "🚀 Deploying..."

            cd ~/TeamSketch

            git pull origin main

            cd backend
            npm install

            # Restart both instances
            # Start backend API
            pm2 restart app || pm2 start src/app.js --name app -- 5000

            # Start whiteboard socket server
            pm2 restart whiteboardServer || pm2 start src/whiteboardServer.js --name whiteboardServer -- 4000

            pm2 save

            sudo nginx -t && sudo systemctl reload nginx

            echo "✅ Done!"